version: "3.8"
services:
  database:
    image: mysql:5.7
    container_name: db_exam
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "mourad"
      MYSQL_DATABASE: exam
    ports:
      - "3310:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_exam
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOSTS: database
      PMA_PORT: 3310
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_exam
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev

  www:
    build: php
    container_name: www_exam
    ports:
      - "2512:80"
    volumes:
      - ../:/var/www/exam
      - ./php/vhosts:/etc/apache2/sites-enabled
    restart: always
    networks:
      - dev
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

networks:
  dev:

volumes:
  db-data:
